# Generated by Django 4.0.6 on 2022-07-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapeofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='polls.myuser'),
        ),
    ]
