# Generated by Django 4.0.6 on 2022-07-30 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_alter_mediapeofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('contet', models.TextField(null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to=settings.AUTH_USER_MODEL)),
                ('user_likes', models.ManyToManyField(blank=True, related_name='userlike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
