# Generated by Django 4.0.6 on 2022-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_mediapic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapeofile',
            name='image',
            field=models.ImageField(blank=True, default='/profile/SetImageProfile', null=True, upload_to='profile/'),
        ),
    ]
